zip -r DungeonsAndDragonsBasicRules.zip DungeonsAndDragonsBasicRules
mv DungeonsAndDragonsBasicRules.zip DungeonsAndDragonsBasicRules.epub
ebook-convert DungeonsAndDragonsBasicRules.epub DungeonsAndDragonsBasicRules.mobi

